### ISSUE TITLE
Get program and/or IDL information as state in Solana commands

### ISSUE THREAD

**Issue by ebarakos** [smartcontractkit/chainlink-solana#127]
This is not good. This could be addressed when we change this. 
For the moment, leave it as it was
>  For the moment let's load the contract and program here too. Open an issue please to circle back here. You can use program.idl then

_Originally posted by @RodrigoAD in https://github.com/smartcontractkit/chainlink-solana/pull/115#r788686814_

And https://github.com/smartcontractkit/chainlink-solana/pull/115#discussion_r788681842

**Comment by aalu1418** [comment]
multisig code is now in `gauntlet-solana-contracts` to leverage the same program & IDL information as the other contracts: https://github.com/smartcontractkit/chainlink-solana/pull/284
