### ISSUE TITLE
Declare and use the same image for both local env and e2e tests

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-solana#162]
We'd want the same image declared for both local env and e2e tests:

- Ideally once for the same repo, so we use the same image across the board (no difference between local and QA environments)
- Using a repo/image that is publicly available so external contributors have access and can set up their environments

_Originally posted by @krebernisak in https://github.com/smartcontractkit/chainlink-solana/pull/161#r795755601_

**Comment by aalu1418** [comment]
is this still relevant since the e2e tests now build off of develop?

**Comment by aalu1418** [comment]
closing because the e2e tests build a custom CL node image using the develop branches from each repo

the local env can build from specific branches in the CL repo or pull an image
