### ISSUE TITLE
Refactor solana relay to use chain configs

### ISSUE THREAD

**Issue by aalu1418** [smartcontractkit/chainlink-solana#176]
Follow the model set by terra and ethereum in core

**Comment by jmank88** [comment]
Is `expected-genesis-hash` the closest equivalent to chain id for identifying Solana chains? From https://docs.solana.com/clusters:
- devnet: `--expected-genesis-hash EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG`
- testnet: `--expected-genesis-hash 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY`
- mainnet beta: `--expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d`

**Comment by aalu1418** [comment]
#250
