### ISSUE TITLE
Properly document and type all OCR2 magic numbers (Gauntlet + Relay).

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-solana#219]
We should properly document and type all these magic numbers.

_Originally posted by @krebernisak in https://github.com/smartcontractkit/chainlink-solana/pull/217#discussion_r809947270_

**Comment by aalu1418** [comment]
relay document magic numbers: https://github.com/smartcontractkit/chainlink-solana/commit/4b72ca2d231b953262bac45703a78df97173133b
