### ISSUE TITLE
standardize the order of accounts

### ISSUE THREAD

**Issue by aalu1418** [smartcontractkit/chainlink-solana#247]
nit: we could tweak the order here:

```suggestion
    pub token_program: Program<'info, Token>,
    #[account(mut, address = state.load()?.config.token_vault)]
    pub token_vault: Account<'info, TokenAccount>,
    /// CHECK: This is a PDA
    #[account(seeds = [b"vault", state.key().as_ref()], bump = state.load()?.vault_nonce)]
    pub vault_authority: AccountInfo<'info>,
```

Seems reasonable to define the program first, the relevant accounts.

_Originally posted by @krebernisak in https://github.com/smartcontractkit/chainlink-solana/pull/243#discussion_r822396122_

Additional notes:
* > Also wouldn't mind the verbosity of token_vault_authority to make it cleaner.
* will require changes in gauntlet + e2e tests as well
* changing the order of accounts should also be standardized across other functions as well such as `AcceptProposal`, `WithdrawPayment`, and `Initialize`

**Comment by archseer** [comment]
The convention I followed was to list all programs and sysvars last night which was the convention in Anchor: https://github.com/project-serum/anchor/blob/5c5fa7927f515e8a755bbbcf8b72bf7e1d7e3871/tests/cfo/programs/cfo/src/lib.rs#L645-L650

**Comment by krebernisak** [comment]
Ok, that makes sense! I'm closing this issue as `won't fix`.

The inconsistencies I noticed is that while programs are last in structs they are often the first arguments in function calls.
