### ISSUE TITLE
Add explicit names to all CI workflow checks + tweak branch protection rules

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-solana#267]
Some checks like `lint`, `test`, `build (ubuntu-latest, 14.x)` & `format (ubuntu-latest, 14.x)` were removed from branch protection rules as they were not setup properly and blocked some PRs:

- `build (ubuntu-latest, 14.x)` & `format (ubuntu-latest, 14.x)` blocked [asdf and ginkgo updates to bring more in line with terra #256](https://github.com/smartcontractkit/chainlink-solana/pull/256)
- `lint` & `test` blocked [tx simulation + config diff + minor refactor #257](https://github.com/smartcontractkit/chainlink-solana/pull/257)

Notice: there are no names for defined checks so it's hard to figure out what checks do those names actually reference.

Action items:

- Add explicit names to all CI workflow checks so they are easily identifiable
- Check, tweak & improve `on:` workflow triggers in the context of branch protection rules
- Reconfigure branch protection rules as appropriate, considering both `develop` & `main` branches

**Comment by tateexon** [comment]
Changes pushed in https://github.com/smartcontractkit/chainlink-solana/pull/256
