### ISSUE TITLE
Get single data of a off-chain data feed for @chainlink/solana-sdk

### ISSUE THREAD

**Issue by iansamz** [smartcontractkit/chainlink-solana#370]
How does a one the latest round data similar to [EVM chain get latest data](https://docs.chain.link/docs/get-the-latest-price/)
If non is available, show an example for how to get this from `data.onRound ` listener

**Comment by archseer** [comment]
You could wrap the `onRound` listener into a promise, we do that in the tests:

https://github.com/smartcontractkit/chainlink-solana/blob/805ddc7d784165bb509c75b6bda9db0ce82bb405/ts/src/index.test.ts#L94-L101

**Comment by aalu1418** [comment]
closing stale issue
