### ISSUE TITLE
onTransmit report error back to libocr, if error surfaced while the context is still alive

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-solana#58]
We should report this error back to libocr if it happens while libocr context still didn't expire (timeout).

For example, if the `SendAndConfirmTra..` errors immediately, we don't actually report these errors upstream, so libocr assumes success while more information is available.

_Originally posted by @krebernisak in https://github.com/smartcontractkit/chainlink-solana/pull/57#r771674681_

**Comment by aalu1418** [comment]
no longer relevant because TXs are implemented in a separate goroutine in the txmanager

closing in favor of #90
