### ISSUE TITLE
Verifiable Random Function

### ISSUE THREAD

**Issue by AlexLeung** [smartcontractkit/chainlink-solana#59]
How does one get a chainlink random number on Solana? I'm not seeing any function in lib for this or any place in State that would hold the value.

**Comment by krebernisak** [comment]
Hi @AlexLeung, thx for your interest in VRF on Solana!

All I can say right now is that it's not available in this repo ATM, but please do follow our Solana announcements as we'll be bringing a lot of exciting updates in the near future.
