### ISSUE TITLE
Restructure repo to avoid main lib bundling the full (heavy) dependency graph

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-solana#62]
These packages look like they are from the e2e QA testing...is that something we want included in the relay pkg? (it  would be nice to keep the relay module as light weight as possible)

_Originally posted by @aalu1418 in https://github.com/smartcontractkit/chainlink-solana/pull/61#pullrequestreview-836673873_

TODO:

- [ ] Move `tests/e2e` to a separate module (`./ops`), so its deps are not bundled in when using a relay as a lib?
- [ ] Move the monitoring package/app to a separate module, so its deps are not bundled in when using a relay as a lib?

**Comment by aalu1418** [comment]
handled here: https://github.com/smartcontractkit/chainlink-solana/pull/334
