### ISSUE TITLE
Update Gauntlet to support Anchor v0.20

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/chainlink-solana#93]
This probably has some breaking changes. Can you open an story just to update this on gauntlet?

_Originally posted by @RodrigoAD in https://github.com/smartcontractkit/chainlink-solana/pull/91#r781171419_

**Comment by aalu1418** [comment]
Fixed with https://github.com/smartcontractkit/chainlink-solana/pull/91/commits/df18f7dc498b66d4b9caf7911a18180981eeffb9
